[package]
name = "article_parser"
version = "0.0.1"
authors = ["beaumontjonathan <beaumont_jonny@hotmail.co.uk>"]
edition = "2018"

[lib]
name="article_parser"
path="src/lib.rs"

[[bin]]
name = "mybin"
path = "src/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.12.0"
htmlescape = "0.3.1"
chrono = { version = "0.4.11", features = ["serde"] }
regex = "1.3.7"
lazy_static = "1.4.0"
serde_json = "1.0.53"
serde = { version = "1.0.110", features = ["derive"] }

[dev-dependencies]
insta = "0.15.0"
paste = "0.1.7"

